name: Deploy API to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Sync code to VM
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" \
            ./ ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }}:/home/${{ secrets.VM_USERNAME }}/app/

      - name: Configure Firewall on VM to Allow HTTP Traffic (Port 80)
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} << 'EOF'
            sudo ufw allow 80/tcp
            sudo ufw reload
            sudo ufw status
          EOF

      - name: Deploy on VM
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} << 'EOF'
            set -e
            cd ~/app

            # Ensure dependencies are installed
            npm install --no-audit --no-fund

            # Start the app if not running, otherwise reload for zero downtime
            if npx pm2 list | grep -q sayHelloAPI; then
              npx pm2 reload sayHelloAPI
            else
              npx pm2 start server.js --name sayHelloAPI
            fi

            npx pm2 save
          EOF
